### ISSUE TITLE
Windows install

### ISSUE THREAD

**Issue by ofek** [bastibe/SoundCard#15] opened 2018-05-20 00:13 UTC
Great lib!

After `pip install SoundCard` I'm getting this:

```
$ python -c "import soundcard"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\soundcard\__init__.py", line 8, in <module>
    from soundcard.mediafoundation import *
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\soundcard\mediafoundation.py", line 14, in <module>
    _combase = _ffi.dlopen('combase')
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\cffi\api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\cffi\api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\Ofek\Desktop\q\Miniconda3\lib\site-packages\cffi\api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: ctypes.util.find_library() did not manage to locate a library called 'combase'
```

**Comment by bastibe** [comment] 2018-05-22 09:48
What version of Python and Windows are you using?

**Comment by bastibe** [comment] 2018-05-23 06:57
I don't have a Windows 7 machine, so this is difficult to debug for me. From some internet discussions it seems that combase.dll only ships with Windows >= 8. It also seems that combase.dll is part of the .NET framework.

Can you try installing [the .NET framework](https://www.microsoft.com/net) and see if that fixes the issue?

**Comment by SoftTacos** [comment] 2018-07-18 22:48
I have run into this same issue with both python 2.7 and 3.7, I installed the .NET core runtime environment, restarted my system just incase, and still get the error. Any ideas?

**Comment by bastibe** [comment] 2018-07-19 07:44
OK, so this appears not to be part of .NET. Can you try installing a recent-ish [MSVC Redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)? Make sure to install the same bitness as your Python (32 or 64, depending on which version of Python you installed).

**Comment by SoftTacos** [comment] 2018-07-19 14:43
Alright, just to be super clear, I went to the link provided and installed "x86: vc_redist.x86.exe" after running "import platform; platform.architecture()" in python3.7 to check my version and it was 32bit. However, after installing it, restarting my computer, and then running my test script (it just imports soundcard), I got the error "Cannot load library [path]\combase.dll", I suspect that this could be because I tried unsuccessfully to install combase.dll prior to asking for your help with "regsvr32 combase.dll". So I removed the old combase.dll from sys32 and sysWOW64(since apparently sysWOW64 contains the 32bit dlls), uninstalled the MSVC redistributable, reinstalled it, restarted my computer, and attempted to use the "repair" option on the MSVC installer, but there is still no combase.dll, and python still throws the "did not manage to locate a library called 'combase'".

**Comment by bastibe** [comment] 2018-07-20 07:48
Thank you for your efforts troubleshooting this issue!

We have learned so far, that Windows 7 does not ship a combase.dll, and it it is not included in the .NET runtime environment, and it is not included in the MSVC redistributable. You *could* try to install the Windows SDK and see if it is included, there. On the other hand, one shouldn't have to install the software development kit just to run some software. There has to be a better way/something we are missing.

Currently, I see three variants of how this is supposed to be done:
- We are supposed to ship combase.dll and friends ourselves (taken from the SDK)
- The libraries have a different name on Windows 7
- There is some other redistributable/runtime we need to install

Honestly, I have no idea. Do you?

**Comment by bastibe** [comment] 2018-07-20 08:06
There's more discussion about this [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/9ad1dcb7-3521-4e80-9023-fd26ccb76a0c/taskstart-on-net-core-throws-missing-combasedll-error-on-windows-7-dev-machine). which seems to imply that... it just won't work on Windows 7? That doesn't sound right.

**Comment by bastibe** [comment] 2018-07-21 10:08
Can you check which functions are missing if you comment out [mediafoundation.py:15](https://github.com/bastibe/SoundCard/blob/master/soundcard/mediafoundation.py#L15)? Maybe that way we can figure out what library we need to load.

**Comment by tcanders** [comment] 2018-12-04 21:54
Hi there, just confirming this issue on my 64-bit Win7. Made some attempts to install the combase.dll file but it doesn't seem to be compatible.

Commenting out line 15 gives
```
$ python -c "import soundcard"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\soundcard\__init__.py", line 13, in <module>
    from soundcard.mediafoundation import *
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\soundcard\mediafoundation.py", line 97, in <module>
    _com = _COMLibrary()
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\soundcard\mediafoundation.py", line 30, in __init__
    hr = _combase.CoInitializeEx(_ffi.NULL, COINIT_MULTITHREADED)
NameError: name '_combase' is not defined
Exception ignored in: <function _COMLibrary.__del__ at 0x066DF978>
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\soundcard\mediafoundation.py", line 55, in __del__
    if self.com_loaded:
AttributeError: '_COMLibrary' object has no attribute 'com_loaded'
```
I'll probably switch over to Ubuntu.

**Comment by bastibe** [comment] 2018-12-05 09:41
I wish I had a better answer than this, but I don't have access to any Windows 7 machine, so I can't debug this. Sorry.

**Comment by c0d3s1ing3r** [comment] 2019-06-24 06:48
I can confirm that installing the Windows SDK does not fix the issue.
In addition, porting over a friend's Windows 10 combase.dll and trying to `regsvr32 combase.dll` it doesn't work either.

**Comment by demberto** [comment] 2020-05-15 12:10
_I don't know a lot of git, so I couldn't open a PR (I wasted about an hour, in vain)._
This has got nothing to do with .NET framework or Windows SDK.
combase.dll was indeed introduced in Windows 8 for purposes unknown to me.
All the functions accessed by the `_combase` object (combase.dll) are also present in `_ole32` object (ole32.dll). And all these APIs you use were introduced in Vista (WASAPI, MMDevice etc.).
So just remove the `_combase` initialisation and replace all **_combase.** with **_ole32.** and instantly all code will run on Vista and above.
Also, according to [this](https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nn-audioclient-iaudioclient#remarks), you need to switch to STA threading model for Windows 8.
Hence, use the `COINIT_APARTMENTTHREADED` flag when calling `CoInitializeEx`.

**Comment by bastibe** [comment] 2020-05-18 13:33
Thank you, @demberto, this is great news!

Would anyone want to take a stab at creating a pull request for making SoundCard work on Windows 7?

**Comment by bastibe** [comment] 2020-05-27 06:19
This has been fixed in the latest version.

Please reopen if the issue persists.

**Closed by bastibe** 2020-05-27 06:19 UTC
